USE QUANLYBANHANG;

go

CREATE FUNCTION A1 (@MAKH NVARCHAR(20) )
RETURNS TABLE
AS
RETURN
SELECT   HOTEN ,DCHI, SODT,NGSINH ,DOANHSO,NGDK
FROM   KHACHHANG
WHERE MAKH = @MAKH;

SELECT  * FROM A1('KH02')
SELECT  * FROM A1('KH08')
SELECT  * FROM A1('KH09')

-- 
GO
CREATE FUNCTION A2 ( @DVT NVARCHAR(20) )
RETURNS TABLE
AS
RETURN
SELECT   MASP,TENSP
FROM   SANPHAM
WHERE DVT = @DVT;

SELECT  * FROM A2('cay')
SELECT  * FROM A2('tui')
SELECT  * FROM A2('quen')

go
---
CREATE FUNCTION A3 (@MANV VARCHAR(20))
RETURNS  TABLE
AS
RETURN
SELECT  SUM(TRIGIA) AS TONG_TRI_GIA FROM NHANVIEN NV
JOIN HOADON HD ON  HD.MANV = NV.MANV
WHERE NV.MANV = @MANV
GROUP BY NV.MANV

SELECT  * FROM A3('NV00')
SELECT  * FROM A3('NV02')
SELECT  * FROM A3('NV04')

-- 
Go
CREATE FUNCTION A4 (@MANV VARCHAR(20))
RETURNS  TABLE
AS
RETURN
SELECT  COUNT(HD.SOHD) AS SL_HD FROM NHANVIEN NV
JOIN HOADON HD ON  HD.MANV = NV.MANV
WHERE NV.MANV = @MANV
GROUP BY NV.MANV

SELECT  * FROM A4('NV03')
SELECT  * FROM A4('NV05')
SELECT  * FROM A4('NV10')


GO
CREATE FUNCTION A5 (@DOANHSO INT)
RETURNS  TABLE
AS
RETURN

  SELECT  count (*) AS SL FROM KHACHHANG
  WHERE  DOANHSO > @DOANHSO

  SELECT  * FROM A5(200000)
SELECT  * FROM A5(1000000)
SELECT  * FROM A5(5000000)

--





GO
CREATE FUNCTION A6 (@NUOCSX VARCHAR(20))
RETURNS  TABLE
AS
RETURN
SELECT  COUNT (NUOCSX) as SL
FROM SANPHAM 
WHERE NUOCSX =  @NUOCSX

SELECT  * FROM A6('Phap')
SELECT  * FROM A6('Trung Quoc')
SELECT  * FROM A6('vIET nam')

--
CREATE FUNCTION A7 (@GIA INT)
RETURNS  TABLE
AS
RETURN
  SELECT  count (*) AS SL FROM SANPHAM
  WHERE  GIA > @GIA

  SELECT  * FROM A7(10000)
SELECT  * FROM A7(50000)
SELECT  * FROM A7(1000000)

--
CREATE FUNCTION A8 (@THANG INT ,@NAM INT)
RETURNS  TABLE
AS
RETURN
 select SUM (TRIGIA) AS TONG_DOAN_THU from HOADON
where   year(NGHD)  = @NAM and MONTH(NGHD) =@THANG



SELECT * FROM A8 (10,2006)
SELECT * FROM A8 (01,2007)
SELECT * FROM A8 (04,2008)

------

CREATE FUNCTION A9 (@NAM INT)
RETURNS  TABLE
AS
RETURN
SELECT DISTINCT SUM(CT.SL) AS SL_sP FROM  CTHD CT
JOIN HOADON HD  ON CT.SOHD = HD.SOHD
WHERE  YEAR (HD.NGHD) = @NAM

SELECT * FROM A9(2006)
SELECT * FROM A9(2007)
SELECT * FROM A9(2008)

---
CREATE FUNCTION A10 (@NAM INT)
RETURNS  TABLE
AS
RETURN
 select SUM (TRIGIA) AS TONG_DOAN_THU from HOADON
where   year(NGHD)  = @NAM 

SELECT * FROM A10(2006)
SELECT * FROM A10(2007)
SELECT * FROM A1(2005)
--

USE QUANLYDETAI
GO

CREATE FUNCTION B_1 (@MSSV INT)
RETURNS  TABLE
AS
RETURN
SELECT  TENSV, SODT, LOP, DIACHI
FROM SINHVIEN
WHERE  MSSV = @MSSV

SELECT * FROM B_1(13520001)
SELECT * FROM B_1(13520005)
SELECT * FROM B_1(13520008)

---
CREATE FUNCTION B_2 (@DIACHI NVARCHAR(20))
RETURNS  TABLE
AS
RETURN
SELECT  TENSV
FROM SINHVIEN
WHERE  DIACHI = @DIACHI

SELECT * FROM B_2(N'QUẬN 1')
SELECT * FROM B_2(N'THỦ ĐỨC')
SELECT * FROM B_2(N'GÒ VẤP')
-- B3
CREATE FUNCTION B_3 (@MSDT INT)
RETURNS  TABLE
AS
RETURN
SELECT  TENSV, SV.MSSV
FROM  SINHVIEN  SV
JOIN SV_DETAI SV_DT ON SV.MSSV = SV_DT.MSSV
WHERE SV_DT.MSDT = @MSDT

SELECT * FROM B_3 (97004)

SELECT * FROM B_3 (97005)

SELECT * FROM B_3 (97011)

--



CREATE FUNCTION B_4()  
RETURNS TABLE  
AS  
 RETURN (SELECT MSGV, TENGV FROM
GIAOVIEN  
WHERE MSGV  not in(
     SELECT gv.MSGV FROM 
GIAOVIEN  gv 
  join GV_PBDT pb on pb.MSGV = gv.MSGV)  )

  select * from B_4()
  ---
